package me.lemphis.realestatepublicbatch.job.buildingregister.owner

import java.math.BigDecimal

data class OwnerFileSpec(
    var 관리건축물대장PK: String? = null,
    var 시군구코드: String? = null,
    var 시군구명: String? = null,
    var 법정동코드: String? = null,
    var 법정동명: String? = null,
    var 대지구분코드: String? = null,
    var 대지구분명: String? = null,
    var 번: String? = null,
    var 지: String? = null,
    var 특수지명: String? = null,
    var 블록: String? = null,
    var 로트: String? = null,
    var 새주소대지위치: String? = null,
    var 새주소도로코드: String? = null,
    var 새주소법정동코드: String? = null,
    var 새주소지상지하코드: String? = null,
    var 새주소지상지하명: String? = null,
    var 새주소본번: String? = null,
    var 새주소부번: String? = null,
    var 대장구분코드: String? = null,
    var 대장구분명: String? = null,
    var 대장종류코드: String? = null,
    var 대장종류명: String? = null,
    var 건물명: String? = null,
    var 동명칭: String? = null,
    var 호명칭: String? = null,
    var 면적: BigDecimal? = null,
    var 소유구분코드: String? = null,
    var 소유구분명: String? = null,
    var 변동원인일: String? = null,
) {
    fun toOwner() = Owner(
        관리건축물대장PK = 관리건축물대장PK!!.trim(),
        시군구코드 = 시군구코드?.trim()?.ifEmpty { null },
        시군구명 = 시군구명?.trim()?.ifEmpty { null },
        법정동코드 = 법정동코드?.trim()?.ifEmpty { null },
        법정동명 = 법정동명?.trim()?.ifEmpty { null },
        대지구분코드 = 대지구분코드?.trim()?.ifEmpty { null },
        대지구분명 = 대지구분명?.trim()?.ifEmpty { null },
        번 = 번?.trim()?.ifEmpty { null },
        지 = 지?.trim()?.ifEmpty { null },
        특수지명 = 특수지명?.trim()?.ifEmpty { null },
        블록 = 블록?.trim()?.ifEmpty { null },
        로트 = 로트?.trim()?.ifEmpty { null },
        새주소대지위치 = 새주소대지위치?.trim()?.ifEmpty { null },
        새주소도로코드 = 새주소도로코드?.trim()?.ifEmpty { null },
        새주소법정동코드 = 새주소법정동코드?.trim()?.ifEmpty { null },
        새주소지상지하코드 = 새주소지상지하코드?.trim()?.ifEmpty { null },
        새주소지상지하명 = 새주소지상지하명?.trim()?.ifEmpty { null },
        새주소본번 = 새주소본번?.trim()?.ifEmpty { null },
        새주소부번 = 새주소부번?.trim()?.ifEmpty { null },
        대장구분코드 = 대장구분코드?.trim()?.ifEmpty { null },
        대장구분명 = 대장구분명?.trim()?.ifEmpty { null },
        대장종류코드 = 대장종류코드?.trim()?.ifEmpty { null },
        대장종류명 = 대장종류명?.trim()?.ifEmpty { null },
        건물명 = 건물명?.trim()?.ifEmpty { null },
        동명칭 = 동명칭?.trim()?.ifEmpty { null },
        호명칭 = 호명칭?.trim()?.ifEmpty { null },
        면적 = 면적,
        소유구분코드 = 소유구분코드?.trim()?.ifEmpty { null },
        소유구분명 = 소유구분명?.trim()?.ifEmpty { null },
        변동원인일 = 변동원인일?.trim()?.ifEmpty { null },
    )
}
