services:
  mysql:
    container_name: mysql
    image: mysql:8.0.29
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service
    ports:
      - "3306:3306"
    volumes:
      - /Users/jaeho/data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-log-bin
      - --innodb_buffer_pool_size=2G
      - --key_buffer_size=0
      - --innodb_lock_wait_timeout=5
