spring:
  application:
    name: real-estate-public-batch
  datasource:
    url: jdbc:mysql://localhost:3306/service?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      auto-commit: false
  batch:
    job:
      name: ${job.name:NONE}
