package me.lemphis.realestatepublicbatch.buildingregister.area

import java.math.BigDecimal

data class AreaFileSpec(
	var 관리건축물대장PK: String? = null,
	var 대장구분코드: String? = null,
	var 대장구분코드명: String? = null,
	var 대장종류코드: String? = null,
	var 대장종류코드명: String? = null,
	var 대지위치: String? = null,
	var 도로명대지위치: String? = null,
	var 건물명: String? = null,
	var 시군구코드: String? = null,
	var 법정동코드: String? = null,
	var 대지구분코드: String? = null,
	var 번: String? = null,
	var 지: String? = null,
	var 특수지명: String? = null,
	var 블록: String? = null,
	var 로트: String? = null,
	var 새주소도로코드: String? = null,
	var 새주소법정동코드: String? = null,
	var 새주소지상지하코드: String? = null,
	var 새주소본번: Int? = null,
	var 새주소부번: Int? = null,
	var 동명: String? = null,
	var 호명: String? = null,
	var 층구분코드: String? = null,
	var 층구분코드명: String? = null,
	var 층번호: Int? = null,
	var 전유공용구분코드: String? = null,
	var 전유공용구분코드명: String? = null,
	var 주부속구분코드: String? = null,
	var 주부속구분코드명: String? = null,
	var 층번호명: String? = null,
	var 구조코드: String? = null,
	var 구조코드명: String? = null,
	var 기타구조: String? = null,
	var 주용도코드: String? = null,
	var 주용도코드명: String? = null,
	var 기타용도: String? = null,
	var 면적: BigDecimal? = null,
	var 생성일자: String? = null,
) {
	fun toArea() = Area(
		관리건축물대장PK = 관리건축물대장PK!!.trim(),
		대장구분코드 = 대장구분코드?.ifBlank { null },
		대장구분코드명 = 대장구분코드명?.ifBlank { null },
		대장종류코드 = 대장종류코드?.ifBlank { null },
		대장종류코드명 = 대장종류코드명?.ifBlank { null },
		대지위치 = 대지위치?.ifBlank { null },
		도로명대지위치 = 도로명대지위치?.ifBlank { null },
		건물명 = 건물명?.ifBlank { null },
		시군구코드 = 시군구코드?.ifBlank { null },
		법정동코드 = 법정동코드?.ifBlank { null },
		대지구분코드 = 대지구분코드?.ifBlank { null },
		번 = 번?.ifBlank { null },
		지 = 지?.ifBlank { null },
		특수지명 = 특수지명?.ifBlank { null },
		블록 = 블록?.ifBlank { null },
		로트 = 로트?.ifBlank { null },
		새주소도로코드 = 새주소도로코드?.ifBlank { null },
		새주소법정동코드 = 새주소법정동코드?.ifBlank { null },
		새주소지상지하코드 = 새주소지상지하코드?.ifBlank { null },
		새주소본번 = 새주소본번,
		새주소부번 = 새주소부번,
		동명 = 동명?.ifBlank { null },
		호명 = 호명?.ifBlank { null },
		층구분코드 = 층구분코드?.ifBlank { null },
		층구분코드명 = 층구분코드명?.ifBlank { null },
		층번호 = 층번호,
		전유공용구분코드 = 전유공용구분코드?.ifBlank { null },
		전유공용구분코드명 = 전유공용구분코드명?.ifBlank { null },
		주부속구분코드 = 주부속구분코드?.ifBlank { null },
		주부속구분코드명 = 주부속구분코드명?.ifBlank { null },
		층번호명 = 층번호명?.ifBlank { null },
		구조코드 = 구조코드?.ifBlank { null },
		구조코드명 = 구조코드명?.ifBlank { null },
		기타구조 = 기타구조?.ifBlank { null },
		주용도코드 = 주용도코드?.ifBlank { null },
		주용도코드명 = 주용도코드명?.ifBlank { null },
		기타용도 = 기타용도?.ifBlank { null },
		면적 = 면적,
		생성일자 = 생성일자?.ifBlank { null },
	)
}
