package me.lemphis.realestatepublicbatch.buildingregister.unit

data class UnitFileSpec(
	var 관리건축물대장PK: String? = null,
	var 대장구분코드: String? = null,
	var 대장구분코드명: String? = null,
	var 대장종류코드: String? = null,
	var 대장종류코드명: String? = null,
	var 대지위치: String? = null,
	var 도로명대지위치: String? = null,
	var 건물명: String? = null,
	var 시군구코드: String? = null,
	var 법정동코드: String? = null,
	var 대지구분코드: String? = null,
	var 번: String? = null,
	var 지: String? = null,
	var 특수지명: String? = null,
	var 블록: String? = null,
	var 로트: String? = null,
	var 새주소도로코드: String? = null,
	var 새주소법정동코드: String? = null,
	var 새주소지상지하코드: String? = null,
	var 새주소본번: Int? = null,
	var 새주소부번: Int? = null,
	var 동명: String? = null,
	var 호명: String? = null,
	var 층구분코드: String? = null,
	var 층구분코드명: String? = null,
	var 층번호: Int? = null,
	var 생성일자: String? = null,
) {
	fun toUnit() = Unit(
		관리건축물대장PK = 관리건축물대장PK!!.trim(),
		대장구분코드 = 대장구분코드?.trim()?.ifEmpty { null },
		대장구분코드명 = 대장구분코드명?.trim()?.ifEmpty { null },
		대장종류코드 = 대장종류코드?.trim()?.ifEmpty { null },
		대장종류코드명 = 대장종류코드명?.trim()?.ifEmpty { null },
		대지위치 = 대지위치?.trim()?.ifEmpty { null },
		도로명대지위치 = 도로명대지위치?.trim()?.ifEmpty { null },
		건물명 = 건물명?.trim()?.ifEmpty { null },
		시군구코드 = 시군구코드?.trim()?.ifEmpty { null },
		법정동코드 = 법정동코드?.trim()?.ifEmpty { null },
		대지구분코드 = 대지구분코드?.trim()?.ifEmpty { null },
		번 = 번?.trim()?.ifEmpty { null },
		지 = 지?.trim()?.ifEmpty { null },
		특수지명 = 특수지명?.trim()?.ifEmpty { null },
		블록 = 블록?.trim()?.ifEmpty { null },
		로트 = 로트?.trim()?.ifEmpty { null },
		새주소도로코드 = 새주소도로코드?.trim()?.ifEmpty { null },
		새주소법정동코드 = 새주소법정동코드?.trim()?.ifEmpty { null },
		새주소지상지하코드 = 새주소지상지하코드?.trim()?.ifEmpty { null },
		새주소본번 = 새주소본번,
		새주소부번 = 새주소부번,
		동명 = 동명?.trim()?.ifEmpty { null },
		호명 = 호명?.trim()?.ifEmpty { null },
		층구분코드 = 층구분코드?.trim()?.ifEmpty { null },
		층구분코드명 = 층구분코드명?.trim()?.ifEmpty { null },
		층번호 = 층번호,
		생성일자 = 생성일자?.trim()?.ifEmpty { null },
	)
}
