package me.lemphis.realestatepublicbatch.buildingregister.houseprice

data class HousePriceFileSpec(
	var 관리건축물대장PK: String? = null,
	var 대장구분코드: String? = null,
	var 대장구분코드명: String? = null,
	var 대장종류코드: String? = null,
	var 대장종류코드명: String? = null,
	var 대지위치: String? = null,
	var 도로명대지위치: String? = null,
	var 건물명: String? = null,
	var 시군구코드: String? = null,
	var 법정동코드: String? = null,
	var 대지구분코드: String? = null,
	var 번: String? = null,
	var 지: String? = null,
	var 특수지명: String? = null,
	var 블록: String? = null,
	var 로트: String? = null,
	var 외필지수: Int? = null,
	var 새주소도로코드: String? = null,
	var 새주소법정동코드: String? = null,
	var 새주소지상지하코드: String? = null,
	var 새주소본번: Int? = null,
	var 새주소부번: Int? = null,
	var 기준일자: String? = null,
	var 주택가격: Long? = null,
	var 생성일자: String? = null,
) {
	fun toHousePrice() = HousePrice(
		관리건축물대장PK = 관리건축물대장PK!!.trim(),
		대장구분코드 = 대장구분코드?.ifBlank { null },
		대장구분코드명 = 대장구분코드명?.ifBlank { null },
		대장종류코드 = 대장종류코드?.ifBlank { null },
		대장종류코드명 = 대장종류코드명?.ifBlank { null },
		대지위치 = 대지위치?.ifBlank { null },
		도로명대지위치 = 도로명대지위치?.ifBlank { null },
		건물명 = 건물명?.ifBlank { null },
		시군구코드 = 시군구코드?.ifBlank { null },
		법정동코드 = 법정동코드?.ifBlank { null },
		대지구분코드 = 대지구분코드?.ifBlank { null },
		번 = 번?.ifBlank { null },
		지 = 지?.ifBlank { null },
		특수지명 = 특수지명?.ifBlank { null },
		블록 = 블록?.ifBlank { null },
		로트 = 로트?.ifBlank { null },
		외필지수 = 외필지수,
		새주소도로코드 = 새주소도로코드?.ifBlank { null },
		새주소법정동코드 = 새주소법정동코드?.ifBlank { null },
		새주소지상지하코드 = 새주소지상지하코드?.ifBlank { null },
		새주소본번 = 새주소본번,
		새주소부번 = 새주소부번,
		기준일자 = 기준일자?.ifBlank { null },
		주택가격 = 주택가격,
		생성일자 = 생성일자?.ifBlank { null },
	)
}
