package me.lemphis.realestatepublicbatch.job.buildingregister.floor

data class Floor(
	val 관리건축물대장PK: String,
	val 대지위치: String? = null,
	val 도로명대지위치: String? = null,
	val 건물명: String? = null,
	val 시군구코드: String? = null,
	val 법정동코드: String? = null,
	val 대지구분코드: String? = null,
	val 번: String? = null,
	val 지: String? = null,
	val 특수지명: String? = null,
	val 블록: String? = null,
	val 로트: String? = null,
	val 새주소도로코드: String? = null,
	val 새주소법정동코드: String? = null,
	val 새주소지상지하코드: String? = null,
	val 새주소본번: Int? = null,
	val 새주소부번: Int? = null,
	val 동명: String? = null,
	val 층구분코드: String? = null,
	val 층구분코드명: String? = null,
	val 층번호: Int? = null,
	val 층번호명: String? = null,
	val 구조코드: String? = null,
	val 구조코드명: String? = null,
	val 기타구조: String? = null,
	val 주용도코드: String? = null,
	val 주용도코드명: String? = null,
	val 기타용도: String? = null,
	val 면적: String? = null,
	val 주부속구분코드: String? = null,
	val 주부속구분코드명: String? = null,
	val 면적제외여부: String? = null,
	val 생성일자: String? = null,
)
